### ISSUE TITLE
Magento 2 - Installation

### ISSUE THREAD

**Issue by Sunil-Jacob** [PHOENIX-MEDIA/magento2-cloud-build#1]
Hi,

I tried pulling your Docker image `phoenixmedia/magento2:2.4.5` 

<img width="1001" alt="image" src="https://user-images.githubusercontent.com/89004489/199453574-94cd6091-efef-4630-99fc-a1652d2d20b5.png">

But I do not get `Agree & Continue` not coming.

**Comment by phoenix-bjoern** [comment]
You probably forgot to provide required env variables for ece-tools.
I recommend to follow this guide: https://medium.com/swlh/running-magento2-in-kubernetes-part-2-building-the-docker-image-8516c0ed7d48. ece-tools should run the installation on startup of the container automatically.

After docker-composer up you should see this when opening http://localhost:
![Bildschirmfoto 2022-11-08 um 16 19 12](https://user-images.githubusercontent.com/846569/200603514-fe0cf75f-5d3f-4a44-a6da-b0c1ed70c823.png)
