### ISSUE TITLE
Cant copy config.php from dist directory

### ISSUE THREAD

**Issue by domi55** [PHOENIX-MEDIA/magento2-cloud-build#2]
Hi bjoern

I currently receive an issue when i try to build the default phoenix media magento 2 image
The build says it can not copy `config.php` last line:

```
  - Installing phoenix-media/magento2-cloud-build (1.0.28): Extracting archive
  0/19 [>---------------------------]   0%
  6/19 [========>-------------------]  31%
  8/19 [===========>----------------]  42%
 11/19 [================>-----------]  57%
 16/19 [=======================>----]  84%
 19/19 [============================] 100%
3 package suggestions were added by new dependencies, use `composer suggest` to see details.
Package symfony/debug is abandoned, you should avoid using it. Use symfony/error-handler instead.
Package php-cs-fixer/diff is abandoned, you should avoid using it. No replacement was suggested.
Generating autoload files
129 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
cp: can't stat 'vendor/phoenix-media/magento2-cloud-build/dist/config.php': No such file or directory
```

I believe its the `cd ${INSTALL_DIR}` from the current change thats causing this error, because  in the install dir there is no direct vendor directory as child, could this be ? Maybe im wrong.

https://github.com/PHOENIX-MEDIA/magento2-cloud-build/blob/9a313e8f2a9e2b8f5b7556afccc54a50d6ba5f93/bin/px-cloud-build-install#L24

**Comment by phoenix-bjoern** [comment]
@domi55 you are right, the „cd“ at the beginning and the end of the line can be omitted. 
Happy to approve your PR.

**Comment by phoenix-bjoern** [comment]
@domi55 version 1.0.29 has been released which should fix the installation issue.

**Comment by domi55** [comment]
@phoenix-bjoern cool thank you : )
