### ISSUE TITLE
When building is always getting a base_url that it's wrong

### ISSUE THREAD

**Issue by francesco-oghabi** [PHOENIX-MEDIA/magento2-cloud-build#4]
Hi there, after the building of the docker image it generate the env.php file on the fly.
The problem is that inside the env is inserting 

web/unsecure/base_url
web/secure/base_url

and the values are my local environment.

i dont know where it'ts getting this value because it's not saved anywhere in the code (no config, no env)

so when we deploy the chart to helm, this value is not overridden by the MAGENTO_ROUTES base64 encode.

logging to the db is always returning the local env.

**Comment by francesco-oghabi** [comment]
Adding the image


![Schermata del 2024-01-10 21-10-50](https://github.com/PHOENIX-MEDIA/magento2-cloud-build/assets/98045367/cbf2a5f3-7a94-4854-b75e-64c8f7aa16a5)

**Comment by francesco-oghabi** [comment]
okey, we changed some other params in the dockerfile because it wasnt deleting env.php

i still dont know why during dockerfile it was connecting to the local domain.

**Comment by phoenix-bjoern** [comment]
@francesco-di-marcantonio you can omit `MAGENTO_CLOUD_ROUTES` and set `PROJECT_DOMAIN` instead. [This script](https://github.com/PHOENIX-MEDIA/magento2-ece-tools/blob/master/bin/ece-tools-get-cloud-routes) will generate `MAGENTO_CLOUD_ROUTES` [dynamically](https://github.com/PHOENIX-MEDIA/magento2-cloud-build/blob/master/dist/magento2-bin/deploy#L13) for you on deployment.
